# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/15049/Desktop/work/la32r_cpu/la32r_cpu.srcs/sources_1/ip/inst_mem_1/inst_mem.xci
# IP: The module: 'inst_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/15049/Desktop/work/la32r_cpu/la32r_cpu.gen/sources_1/ip/inst_mem_1/inst_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/15049/Desktop/work/la32r_cpu/la32r_cpu.srcs/sources_1/ip/inst_mem_1/inst_mem.xci
# IP: The module: 'inst_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/15049/Desktop/work/la32r_cpu/la32r_cpu.gen/sources_1/ip/inst_mem_1/inst_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
